name: kalileoyuen
favicon: null
layout_spectrum: 0
typography_spectrum: 0.3585654441267252
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#e53947'
    - '#d89693'
    - '#7f7f7f'
    - '#1f1d1e'
  brandStrength: 0.5
  lightness: 0.9655703203752637
  saturation: 0.9696716922335327
  rhythmicContrast: 0.9674018113873899
purpose: []
