analytics: {}
color:
  brandColors:
    - '#ADCAD8'
    - '#EEF3ED'
    - '#273D0C'
    - '#050908'
    - '#002800'
  brandStrength: 0.8125
  lightness: 0.5625
  rhythmicContrast: 0.25
  saturation: 0.9696716922335327
cta: {}
layout_spectrum: 1
name: kalileoyuen
opengraph: {}
purpose: []
typography_spectrum: 0.3585654441267252
